### ISSUE TITLE
Non-git "projects" support

### ISSUE THREAD

**Issue by mbolivar** [zephyrproject-rtos/west#243]
Though west is currently tied to git for projects and the manifest repository, there's no reason it has to stay that way forever. Some ideas for generalization:

- support projects and manifests managed by other version control systems (e.g. hg, p4)
- support projects which are just tarballs (.tar.gz, .tar.xz, .tar.bz2, .zip, .lzma, etc. -- see [dtrx](https://github.com/moonpyk/dtrx) for inspiration)
- support artifacts which are binary objects (e.g. firmware blobs needed by downstream distributions)

**Comment by mbolivar-nordic** [comment]
After getting a couple of years of experience here, I don't think this is worth doing. West is a git wrapper, pretty much by design. Some Zephyr users complained when it was introduced that it was too git specific, but Zephyr uses git, for better or worse. I think it is incumbent upon those users to deal with this as they see fit.

Note that converting between the west.yml format and other formats is possible, I dare say easy, using the west API. I posted an example for this a while back in the list:

https://lists.zephyrproject.org/g/devel/message/6437
