### ISSUE TITLE
Allow manifest to have default/clone-depth

### ISSUE THREAD

**Issue by galak** [zephyrproject-rtos/west#307]
Allow to set clone-depth as a default in the manifest.  A clone-depth set on a specific project should override the default.

**Comment by mbolivar-nordic** [comment]
I'm going to close this as not planned because over time, we've added options like `--fetch-opt`, which address the use case of needing to make shallow clones in CI environments. I believe this use case is what was originally motivating this issue. Please reopen and explain the use case if that's wrong.
